# Generated by RECIPER MVP static analyzer
# Dockerfile for conda environment with version support

FROM continuumio/miniconda3:latest

# Set working directory
WORKDIR /app

# Copy environment.yml (if exists)
COPY environment.yml .

# Update conda environment
RUN conda env update -f environment.yml
# Install packages with versions
RUN conda install -y matplotlib numpy pandas

# Set default command
CMD ["/bin/bash"]
